<?php
require_once __DIR__ . '/../api/api.php';

$slug = $_GET['slug'] ?? '';
if (!$slug) {
    header('Location: core-discovery.php');
    exit;
}

$response = fetchSupabase('articles', 'slug=eq.' . urlencode($slug) . '&select=*');
if (!$response || empty($response)) {
    // Fallback if not found
    header('Location: core-discovery.php');
    exit;
}

$article = $response[0];
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <title><?= htmlspecialchars($article['title']) ?> | Documentation</title>
    <script src="https://cdn.tailwindcss.com?plugins=forms,container-queries,typography"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Geist+Mono:wght@400;500&display=swap" rel="stylesheet"/>
    <script id="tailwind-config">
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        primary: "#0a0a0a",
                        "on-primary": "#ffffff",
                        "brand-green": "#00d4a4",
                        canvas: "#ffffff",
                        surface: "#f7f7f7",
                        hairline: "#e5e5e5",
                        ink: "#0a0a0a",
                        slate: "#3a3a3c",
                        steel: "#5a5a5c",
                    },
                    fontFamily: {
                        sans: ["Inter", "sans-serif"],
                        mono: ["Geist Mono", "monospace"],
                    },
                    borderRadius: { md: "8px", lg: "12px", full: "9999px" }
                }
            }
        }
    </script>
    <style>
        body { background-color: #ffffff; color: #0a0a0a; font-family: 'Inter', sans-serif; }
        
        /* Prose styling to match Mintlify */
        .prose h1, .prose h2, .prose h3 { color: #0a0a0a; font-weight: 600; letter-spacing: -0.5px; }
        .prose p, .prose li { color: #3a3a3c; font-size: 16px; line-height: 1.5; }
        .prose strong { color: #0a0a0a; font-weight: 600; }
        .prose a { color: #0a0a0a; font-weight: 500; border-bottom: 1px solid #e5e5e5; text-decoration: none; transition: border-color 0.2s; }
        .prose a:hover { border-color: #0a0a0a; }
    </style>
</head>
<body class="antialiased selection:bg-brand-green selection:text-primary min-h-screen flex flex-col">

    <!-- Top Navigation (Documentation) -->
    <nav class="fixed top-0 w-full bg-canvas/90 backdrop-blur-md border-b border-hairline z-50 h-[56px] flex items-center px-6 justify-between">
        <div class="flex items-center gap-6">
            <a href="../index.php" class="font-semibold tracking-tight text-lg text-ink">Project Vision</a>
        </div>
        <div class="flex items-center gap-4">
            <a href="core-discovery.php" class="text-sm font-medium text-steel hover:text-ink transition-colors">&larr; Back to Documentation</a>
        </div>
    </nav>

    <div class="flex flex-1 pt-[56px] justify-center">
        <!-- Center Prose (Main Content) -->
        <main class="flex-1 p-8 md:p-12 max-w-[800px] w-full">
            
            <!-- Article Header -->
            <div class="mb-10 border-b border-hairline pb-8">
                <div class="flex items-center gap-3 mb-4">
                    <span class="text-[13px] text-steel font-mono bg-surface px-2 py-1 rounded-sm border border-hairline">
                        <?= date('F j, Y', strtotime($article['created_at'])) ?>
                    </span>
                    <span class="text-[11px] font-semibold text-primary bg-[#00d4a4]/20 px-2 py-1 rounded-sm uppercase tracking-[0.5px]">
                        <?= htmlspecialchars($article['category']) ?>
                    </span>
                </div>
                
                <h1 class="text-[48px] font-semibold text-ink leading-[1.1] tracking-[-1px] mb-6">
                    <?= htmlspecialchars($article['title']) ?>
                </h1>
                
                <p class="text-[18px] text-slate leading-[1.5] mb-8">
                    <?= htmlspecialchars($article['raw_abstract']) ?>
                </p>

                <?php if (!empty($article['image_url'])): ?>
                <div class="w-full rounded-lg overflow-hidden border border-hairline bg-surface">
                    <img src="<?= htmlspecialchars($article['image_url']) ?>" alt="Telemetry Image" class="w-full h-auto object-cover max-h-[400px]">
                </div>
                <?php endif; ?>
            </div>

            <!-- Beautified Content generated by Gemini -->
            <article class="prose max-w-none mb-16">
                <?= $article['beautified_content'] ?>
            </article>

            <!-- Footer Meta -->
            <div class="border-t border-hairline pt-6 flex justify-between items-center text-sm text-steel mb-12">
                <div>Source Author: <span class="font-medium text-ink"><?= htmlspecialchars($article['source_author']) ?></span></div>
                <div class="font-mono">UUID: <?= htmlspecialchars($article['id']) ?></div>
            </div>
            
        </main>
    </div>

</body>
</html>
